dist: release
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
- main: .
  binary: sg
  ldflags:
    - -X main.BuildCommit={{.Commit}}
  goos:
    - linux
    - darwin
  goarch:
    - amd64
archives:
- id: bin
  format: binary
  wrap_in_directory: false
  name_template: "sg_{{ .Os }}_{{ .Arch }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
