dist: release
env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go mod tidy
builds:
  - id: linux-build
    main: .
    binary: sg
    ldflags:
      - -X main.BuildCommit={{.Commit}}
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
  - id: darwin-build
    main: .
    binary: sg
    ldflags:
      - -s
      - -X main.BuildCommit={{.Commit}}
    env:
      - CGO_ENABLED=1
      - CC=/home/runner/work/osxcross/target/bin/o64-clang
      - CXX=/home/runner/work/osxcross/target/bin/o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

archives:
- id: bin
  format: binary
  wrap_in_directory: false
  name_template: "sg_{{ .Os }}_{{ .Arch }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
