name: GoReleaser

on:
  push:
    branches:
      - main

jobs:
  goreleaser:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: go test -race -v ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          # Use separate access token, because we need a scope:repo token to publish the brew formula.
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
