name: Test
on: [ pull_request ]

jobs:
  check:
    runs-on: macos-11
    steps:
    - name: Install SG (oneliner)
      shell: 'script --return --quiet --command "zsh {0}"' # force TTY
      run: |
        curl --proto '=https' --tlsv1.2 -sSLf https://install.sg.dev > dl.sh
        yes | sh dl.sh
        sg version
