name: Test
on: [ pull_request ]

jobs:
  check:
    runs-on: macos-11
    steps:
    - name: Install SG (oneliner)
      shell: 'script -q out zsh {0} && cat out' # force TTY
      run: |
        brew info
        curl --proto '=https' --tlsv1.2 -sSLf https://install.sg.dev > dl.sh
        yes | sh dl.sh
        sg version
